version: "2"

run:
  timeout: 10m
  issues-exit-code: 2
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.25'

issues:
  uniq-by-line: true

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
  path-prefix: "./"

linters:
  default: all
  disable:
    - depguard
    - tagliatelle
    - noctx
    - wrapcheck
    - varnamelen
    - nonamedreturns
    - ireturn
    - gochecknoglobals
    - errname
    - exhaustruct
    - containedctx
    - dupl
    - godot
    - nolintlint
    - contextcheck
    - gochecknoinits
    - gocyclo
    - gocognit
    - funlen
    - cyclop
    - tagalign
    - goconst
    - mnd
    - revive
    - funcorder
    - noinlineerr
    - intrange
    - lll
    - wsl
    - wsl_v5
    - gosec
    - gocritic
  settings:
    revive:
      max-open-files: 2048
      severity: error
      enable-all-rules: true
      confidence: 0.1
      rules:
        - name: add-constant
          severity: warning
          disabled: false
          arguments:
            - maxLitCount: "3"
              allowStrs: '""'
              allowInts: "0,1,2,10,32,64"
              allowFloats: "0.0,0.,1.0,1.,2.0,2."
        - name: line-length-limit
          severity: warning
          disabled: false
          arguments: [ 120 ]
        - name: max-public-structs
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: blank-imports
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: get-return
          disabled: true
        - name: redundant-import-alias
          disabled: true
    dupl:
      threshold: 100
    errorlint:
      errorf: true
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 65
      statements: 40
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 10
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - dupImport
        - unnecessaryBlock
    misspell:
      locale: US
    nestif:
      min-complexity: 4
    nolintlint:
      require-explanation: true
      require-specific: true
    tagliatelle:
      case:
        use-field-name: false
        rules:
          json: snake
          yaml: goCamel
          xml: goCamel
          bson: snake
          avro: snake
          mapstructure: kebab
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-assign-and-anything: false
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: true
      allow-separated-leading-comment: false
      allow-cuddle-declarations: false
      allow-cuddle-with-calls: [ "Lock", "RLock" ]
      allow-cuddle-with-rhs: [ "Unlock", "RUnlock" ]
      force-err-cuddling: true
      error-variable-names: [ "err" ]
      force-short-decl-cuddling: false
