port: 8080
postgres:
  url: "port=5432 user=intern password=fyr8as4da6 dbname=banner_db sslmode=disable" #host=banner-bd
redis:
  url: "redis://localhost:6379/0"#"redis://chaches/0"
logger:
  app_name: "banner"
  level: 'debug'
  directory: './app-log/'
  use_std_and_file: true
  allow_show_low_level: true
