version: "3"
volumes:
  postgis-data-test:
  chaches-data-test:
services:
  banner-bd-test:
    image: postgres:16
    expose:
      - "5432"
    command: "postgres -c shared_preload_libraries='pg_stat_statements'"
    volumes:
      - postgis-data-test:/var/lib/postgresql
      - ./script:/docker-entrypoint-initdb.d
    env_file:
      - config/env/api_test.env
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  cron-service:
    image: cron
    networks:
      - default-test
    volumes:
      - ./config/docker-config.yaml:/config.yaml
    environment:
      - CONFIG_PATH=/config.yaml
      - TASK_PERIOD=10
    depends_on:
      - banner-bd-test
    restart: on-failure
  chaches-test:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - chaches-data-test:/data
    restart: always
networks:
  default-test:
    driver: bridge