{
 "title": "Сервис баннеров",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selected_path",
    "label": "selected_path",
    "query": {
     "query": "label_values(main_durations_bucket,path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Успешных запросов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (main_success_hits{path=\"$selected_path\"})",
     "legendFormat": "__auto",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Неуспешных запросов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (main_error_hits{path=\"$selected_path\"})",
     "legendFormat": "__auto",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(main_durations_bucket{path=\"$selected_path\"}[$__rate_interval])))",
     "legendFormat": "__auto",
     "refID": "A"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(main_durations_bucket{path=\"$selected_path\"}[$__rate_interval])))",
     "legendFormat": "__auto",
     "refID": "B"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(main_durations_bucket{path=\"$selected_path\"}[$__rate_interval])))",
     "legendFormat": "__auto",
     "refID": "C"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(main_durations_bucket{path=\"$selected_path\"}[$__rate_interval])))",
     "legendFormat": "__auto",
     "refID": "D"
    }
   ]
  }
 ]
}