port: 8080
mode: release
postgres:
  url: "host=banner-bd-test port=5432 user=intern password=fyr8as4da6 dbname=banner_db sslmode=disable"
  max_connections: 10
  min_connections: 5
  ttl_idle_connections: 100
redis:
  url: "redis://chaches-test/0"
logger:
  app_name: "banner"
  level: 'warn'
  directory: './app-log/'
  use_std_and_file: false
  allow_show_low_level: false
