port: 8080
postgres:
  url: "host=banner-bd port=5432 user=intern password=fyr8as4da6 dbname=banner_db sslmode=disable"
  max_connections: 10
  max_idle_connections: 5
  ttl_idle_connections: 100
redis:
  url: "redis://chaches/0"
logger:
  app_name: "banner"
  level: 'info'
  directory: './app-log/'
  use_std_and_file: false
  allow_show_low_level: false
